ALTER TABLE soft ADD CONSTRAINT softina PRIMARY KEY (id);
ALTER TABLE pcs ADD CONSTRAINT peka PRIMARY KEY (id);
ALTER TABLE rooms ADD CONSTRAINT room PRIMARY KEY (id);
ALTER TABLE employees ADD CONSTRAINT employ PRIMARY KEY (id);
